grafana:
  enabled: true

prometheus:
  enabled: true

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

  extraArgs:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|run/containerd/.+|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|mqueue|proc|pstore|securityfs|sysfs|tracefs)$
